#!/bin/bash
PublicIP=`curl ipinfo.io/ip -s`
IzzyIP="$PublicIP:25565"
BoizIP="$PublicIP:25566"
TimeStamp=`date -u +"%Y-%m-%dT%H:%M:%SZ"`

echo "$PublicIP" > CoupIP
echo "$IzzyIP" > IzzyMinecraft.ip
echo "$BoizIP" > BoizMinecraft.ip
git add --all > /dev/null
git commit -m "$TimeStamp > /dev/null"
git push > /dev/null
